### ISSUE TITLE
Pattern needed

### ISSUE THREAD

**Issue by numerodix** [piskvorky/topic_modeling_tutorial#2]
I was clicking through 0 - Intro & Setup and on this step:
gensim.utils.lemmatize("The quick brown fox jumps over the lazy dog!")

I got this error:
https://groups.google.com/forum/#!msg/gensim/DjsPuqQC_Ig/3I7P_bDHBaEJ

The fix:
pip install Pattern

**Comment by piskvorky** [comment]
I've updated the README install instructions earlier today (incl. `pattern`).

This is all work in progress -- I'll be fleshing the notebooks out this weekend. I appreciate the feedback but please wait a bit :)

**Comment by numerodix** [comment]
Wow, that was fast. I had the browser tab open from this morning. :)
